import {
  Banknote,
  BarChart3,
  Boxes,
  CalendarHeart,
  CalendarPlus,
  CalendarX,
  Clock,
  ClipboardCheck,
  ClipboardList,
  Factory,
  FileText,
  HandCoins,
  HardHat,
  Landmark,
  LayoutDashboard,
  Monitor,
  Package,
  Palmtree,
  Receipt,
  Settings,
  ShoppingCart,
  Stethoscope,
  Tag,
  Target,
  Truck,
  UserCog,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";

import type { MenuEntry, MenuItem } from "./Sidebar.types";

/**
 * Menu do sistema, organizado por módulo.
 *
 * A visibilidade é resolvida em tempo de execução pelo hook useMenu,
 * cruzando `module` (licença da empresa) e `permission` (RBAC do usuário).
 * Um grupo some do menu quando nenhum de seus filhos é visível.
 *
 * Itens com `disabled: true` ainda não foram implementados: aparecem
 * como "em breve" para mostrar o caminho do produto sem levar a 404.
 */
export const menu: MenuEntry[] = [
  {
    id: "visao-geral",
    title: "Visão geral",
    icon: LayoutDashboard,
    iconAnim: "dashboard",
    href: "/",
  },

  {
    id: "cadastros",
    title: "Cadastros",
    icon: Users,
    iconAnim: "users",
    section: "interprise",
    children: [
      {
        id: "parceiros",
        title: "Parceiros",
        icon: Users,
        iconAnim: "users",
        href: "/erp/parceiros",
        module: "BPS",
        permission: "partner.view",
      },
      {
        id: "produtos",
        title: "Produtos",
        icon: Package,
        iconAnim: "package",
        href: "/erp/produtos",
        module: "PRODUCTS",
        permission: "product.view",
      },
    ],
  },

  {
    id: "colaboradores-interprise",
    title: "Colaboradores",
    icon: UserCog,
    iconAnim: "usercog",
    module: "HR",
    section: "interprise",
    children: [
      {
        id: "cadastro-colaboradores-interprise",
        title: "Cadastro de colaboradores",
        icon: Users,
        iconAnim: "users",
        href: "/erp/rh/colaboradores",
        module: "HR",
        permission: "employee.view",
      },
    ],
  },

  {
    id: "compras",
    title: "Compras",
    icon: Truck,
    iconAnim: "truck",
    module: "PURCHASE",
    children: [
      {
        id: "compras-lista",
        title: "Compras",
        icon: Truck,
        iconAnim: "truck",
        href: "/erp/compras",
        module: "PURCHASE",
        permission: "purchase.view",
      },
      {
        id: "cotacoes",
        title: "Cotações",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/compras/cotacoes",
        module: "PURCHASE",
        permission: "quotation.view",
      },
      {
        id: "pedidos-compra",
        title: "Pedidos",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/compras/pedidos",
        module: "PURCHASE",
        permission: "purchase-order.view",
      },
      {
        id: "recebimentos",
        title: "Recebimentos",
        icon: Boxes,
        iconAnim: "boxes",
        href: "/erp/compras/recebimento",
        module: "PURCHASE",
        permission: "purchase.receive",
      },
    ],
  },

  {
    id: "comercial",
    title: "Comercial",
    icon: ShoppingCart,
    iconAnim: "cart",
    module: "SALES",
    children: [
      {
        id: "vendas",
        title: "Vendas",
        icon: ClipboardList,
        iconAnim: "clipboard",
        href: "/erp/vendas",
        module: "SALES",
        permission: "sale.view",
      },
      {
        id: "orcamentos",
        title: "Orçamentos",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/vendas/orcamentos",
        module: "SALES",
        permission: "quote.view",
      },
      {
        id: "pedidos",
        title: "Pedidos",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/vendas/pedidos",
        module: "SALES",
        permission: "sales-order.view",
      },
      {
        id: "vendas-configuracoes",
        title: "Configurações",
        icon: Settings,
        iconAnim: "settings",
        href: "/erp/vendas/configuracoes",
        module: "SALES",
        permission: "sales-settings.view",
      },
    ],
  },

  {
    id: "estoque",
    title: "Estoque",
    icon: Warehouse,
    iconAnim: "warehouse",
    module: "INVENTORY",
    children: [
      {
        id: "estoque-saldo",
        title: "Saldo em estoque",
        icon: Boxes,
        iconAnim: "boxes",
        href: "/erp/estoque",
        module: "INVENTORY",
        permission: "inventory.view",
      },
      {
        id: "movimentacoes",
        title: "Movimentações",
        icon: ClipboardList,
        iconAnim: "clipboard",
        href: "/erp/estoque/movimentacoes",
        module: "INVENTORY",
        permission: "stock-movement.view",
      },
      {
        id: "inventario",
        title: "Contagem de inventário",
        icon: ClipboardCheck,
        iconAnim: "clipboard",
        href: "/erp/estoque/inventario",
        module: "INVENTORY_COUNT",
        permission: "inventory-count.view",
      },
      {
        id: "inventario-acompanhamento",
        title: "Acompanhamento de inventário",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/estoque/inventario/acompanhamento",
        module: "INVENTORY_COUNT",
        permission: "inventory-count-tracking.view",
      },
    ],
  },

  {
    id: "financeiro",
    title: "Financeiro",
    icon: Wallet,
    iconAnim: "wallet",
    module: "FINANCE",
    children: [
      {
        id: "contas-receber",
        title: "Contas a receber",
        icon: Banknote,
        iconAnim: "banknote",
        href: "/erp/financeiro/receber",
        module: "FINANCE",
        permission: "financial-entry.view",
      },
      {
        id: "contas-pagar",
        title: "Contas a pagar",
        icon: Receipt,
        iconAnim: "receipt",
        href: "/erp/financeiro/pagar",
        module: "FINANCE",
        permission: "financial-entry.view",
      },
      {
        id: "fluxo-caixa",
        title: "Fluxo de caixa",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/financeiro/fluxo-caixa",
        module: "FINANCE",
        permission: "financial-entry.view",
      },
      {
        id: "orcamento",
        title: "Orçamento",
        icon: Target,
        iconAnim: "target",
        href: "/erp/financeiro/orcamento",
        module: "FINANCE",
        permission: "budget.view",
      },
      {
        id: "contas-bancarias",
        title: "Contas Bancárias",
        icon: Landmark,
        iconAnim: "landmark",
        href: "/erp/financeiro/contas-bancarias",
        module: "FINANCE",
        permission: "bank-account.view",
      },
    ],
  },

  {
    id: "rh",
    title: "Recursos Humanos",
    icon: UserCog,
    iconAnim: "usercog",
    module: "HR",
    children: [
      {
        id: "epi",
        title: "Ficha de EPI",
        icon: HardHat,
        iconAnim: "hardhat",
        href: "/erp/rh/epi",
        module: "HR",
        permission: "ppe-delivery.view",
      },
      {
        id: "exames",
        title: "Exames médicos",
        icon: Stethoscope,
        iconAnim: "stethoscope",
        href: "/erp/rh/exames",
        module: "HR",
        permission: "employee.view",
      },
      {
        id: "aniversariantes",
        title: "Aniversariantes",
        icon: CalendarHeart,
        iconAnim: "calendarheart",
        href: "/erp/rh/aniversariantes",
        module: "HR",
        permission: "employee.view",
      },
      {
        id: "etiquetas-ctps",
        title: "Etiquetas CTPS",
        icon: Tag,
        iconAnim: "tag",
        href: "/erp/rh/etiquetas-ctps",
        module: "HR",
        permission: "employee.view",
      },
      {
        id: "indicadores-rh",
        title: "Indicadores",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/rh/indicadores",
        module: "HR",
        permission: "employee.view",
      },
      {
        id: "controle-ponto",
        title: "Controle de ponto",
        icon: Clock,
        iconAnim: "clock",
        href: "/erp/rh/ponto",
        module: "LABOR",
        permission: "time-entry.view",
      },
      {
        id: "acompanhamento-horas",
        title: "Acompanhamento de horas",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/rh/ponto/acompanhamento",
        module: "LABOR",
        permission: "time-entry.view",
      },
      {
        id: "faltas-abonos",
        title: "Faltas e abonos",
        icon: CalendarX,
        iconAnim: "calendarx",
        href: "/erp/rh/faltas",
        module: "LABOR",
        permission: "absence-record.view",
      },
      {
        id: "folha-pagamento",
        title: "Folha de pagamento",
        icon: Banknote,
        iconAnim: "banknote",
        href: "/erp/rh/folha",
        module: "LABOR",
        permission: "payroll.view",
      },
      {
        id: "decimo-terceiro",
        title: "13º salário",
        icon: Wallet,
        iconAnim: "wallet",
        href: "/erp/rh/decimo-terceiro",
        module: "LABOR",
        permission: "thirteenth-salary.view",
      },
      {
        id: "ferias",
        title: "Férias",
        icon: Palmtree,
        iconAnim: "palmtree",
        href: "/erp/rh/ferias",
        module: "LABOR",
        permission: "vacation.view",
      },
      {
        id: "programacao-ferias",
        title: "Programação de férias",
        icon: CalendarPlus,
        iconAnim: "calendarplus",
        href: "/erp/rh/ferias/programacao",
        module: "LABOR",
        permission: "vacation.create",
      },
      {
        id: "adiantamentos",
        title: "Adiantamento Salarial",
        icon: HandCoins,
        iconAnim: "handcoins",
        href: "/erp/rh/adiantamentos",
        module: "LABOR",
        permission: "salary-advance.view",
      },
    ],
  },

  {
    id: "producao",
    title: "Produção",
    icon: Factory,
    iconAnim: "factory",
    module: "PRODUCTION",
    children: [
      {
        id: "ordens-producao",
        title: "Ordens de produção",
        icon: ClipboardList,
        iconAnim: "clipboard",
        href: "/erp/producao/ordens",
        module: "PRODUCTION",
        permission: "production-order.view",
      },
      {
        id: "acompanhamento",
        title: "Acompanhamento",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/producao/acompanhamento",
        module: "PRODUCTION",
        permission: "production-order.view",
      },
    ],
  },

  {
    id: "dashboard",
    title: "Dashboard",
    icon: LayoutDashboard,
    iconAnim: "dashboard",
    children: [
      {
        id: "dashboard-graficos-colaboradores",
        title: "Gráficos colaboradores",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/rh/graficos-colaboradores",
        module: "HR",
        permission: "employee.view",
      },
      {
        id: "dashboard-graficos-fluxo-caixa",
        title: "Gráficos fluxo de caixa",
        icon: BarChart3,
        iconAnim: "chart",
        href: "/erp/financeiro/graficos-fluxo-caixa",
        module: "FINANCE",
        permission: "financial-entry.view",
      },
    ],
  },

  {
    id: "relatorios",
    title: "Relatórios",
    icon: FileText,
    iconAnim: "filetext",
    children: [
      {
        id: "relatorio-produtos",
        title: "Produtos",
        icon: Package,
        iconAnim: "package",
        href: "/erp/produtos/relatorio",
        module: "PRODUCTS",
        permission: "product.report",
      },
      {
        id: "relatorio-funcoes",
        title: "Funções",
        icon: ClipboardList,
        iconAnim: "clipboard",
        href: "/erp/rh/funcoes/relatorio",
        module: "HR",
        permission: "employee.report",
      },
      {
        id: "relatorio-parceiros",
        title: "Parceiros",
        icon: Users,
        iconAnim: "users",
        href: "/erp/parceiros/relatorio",
        module: "BPS",
        permission: "partner.report",
      },
      {
        id: "relatorio-compras",
        title: "Compras",
        icon: Truck,
        iconAnim: "truck",
        href: "/erp/compras/relatorio",
        module: "PURCHASE",
        permission: "purchase.report",
      },
      {
        id: "relatorio-recebimentos",
        title: "Recebimentos",
        icon: Boxes,
        iconAnim: "boxes",
        href: "/erp/compras/recebimento/relatorio",
        module: "PURCHASE",
        permission: "purchase.report",
      },
      {
        id: "relatorio-pedidos-compra",
        title: "Pedidos de compra",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/compras/pedidos/relatorio",
        module: "PURCHASE",
        permission: "purchase.report",
      },
      {
        id: "relatorio-cotacoes",
        title: "Cotações",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/compras/cotacoes/relatorio",
        module: "PURCHASE",
        permission: "purchase.report",
      },
      {
        id: "relatorio-pedidos-venda",
        title: "Pedidos de venda",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/vendas/pedidos/relatorio",
        module: "SALES",
        permission: "sale.report",
      },
      {
        id: "relatorio-orcamentos",
        title: "Orçamentos",
        icon: FileText,
        iconAnim: "filetext",
        href: "/erp/vendas/orcamentos/relatorio",
        module: "SALES",
        permission: "sale.report",
      },
      {
        id: "relatorio-contas-receber",
        title: "Contas a receber",
        icon: Banknote,
        iconAnim: "banknote",
        href: "/erp/financeiro/contas/relatorio?type=RECEIVABLE",
        module: "FINANCE",
        permission: "financial-entry.report",
      },
      {
        id: "relatorio-contas-pagar",
        title: "Contas a pagar",
        icon: Receipt,
        iconAnim: "receipt",
        href: "/erp/financeiro/contas/relatorio?type=PAYABLE",
        module: "FINANCE",
        permission: "financial-entry.report",
      },
      {
        id: "relatorio-exames",
        title: "Exames",
        icon: Stethoscope,
        iconAnim: "stethoscope",
        href: "/erp/rh/exames/relatorio",
        module: "HR",
        permission: "employee.report",
      },
      {
        id: "relatorio-aniversariantes",
        title: "Aniversariantes",
        icon: CalendarHeart,
        iconAnim: "calendarheart",
        href: "/erp/rh/aniversariantes/relatorio",
        module: "HR",
        permission: "employee.report",
      },
      {
        id: "relatorio-encargos",
        title: "Encargos (Folha/13º/Férias)",
        icon: Banknote,
        iconAnim: "banknote",
        href: "/erp/rh/folha/relatorio",
        module: "LABOR",
        permission: "payroll.report",
      },
    ],
  },
];

/**
 * Itens que ainda ficam no menu do usuário (topo direito, avatar) mesmo
 * depois da reorganização em OS: Personalização é o único item
 * duplicado (também vira card em OS) e Ponto-Manual é de uso pessoal do
 * dia a dia, fica só aqui. Usuários/Perfis/Licenciamento/Configurações/
 * Notificações saíram — moraram só dentro do app OS agora
 * (ver frontend/src/app/os/**).
 */
export const systemMenuItems: MenuItem[] = [
  {
    id: "personalizacao",
    title: "Personalização",
    icon: Monitor,
    iconAnim: "monitor",
    href: "/erp/configuracoes/personalizacao",
    // company-branding.view libera a tela inteira (inclusive "Da
    // empresa"); profile.personal libera só a entrada — "Minha conta"
    // é autoatendimento, "Da empresa"/"Geral" ficam escondidas dentro
    // da página pra quem só tem profile.personal (ver page.tsx).
    permission: ["company-branding.view", "profile.personal"],
  },
  {
    id: "ponto-manual",
    title: "Ponto - Manual",
    icon: Clock,
    iconAnim: "clock",
    href: "/erp/ponto-manual",
    module: "LABOR",
    permission: "time-entry.create",
  },
  {
    id: "meu-holerite",
    title: "Meu Holerite",
    icon: FileText,
    iconAnim: "filetext",
    href: "/erp/meu-holerite",
    module: "LABOR",
  },
  {
    id: "minhas-ferias",
    title: "Minhas Férias",
    icon: Palmtree,
    iconAnim: "palmtree",
    href: "/erp/minhas-ferias",
    module: "LABOR",
  },
  {
    id: "minhas-horas",
    title: "Acompanhamento de Horas",
    icon: Clock,
    iconAnim: "clock",
    href: "/erp/rh/ponto/acompanhamento",
    module: "LABOR",
    permission: "time-entry.view",
  },
  {
    id: "meu-epi",
    title: "Minha Ficha de EPI",
    icon: HardHat,
    iconAnim: "hardhat",
    href: "/erp/rh/epi",
    module: "HR",
    permission: "ppe-delivery.view",
  },
];
